# Generated by Django 5.0.3 on 2024-07-17 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('value', models.TextField()),
                ('ftype', models.CharField(choices=[('REPLY', 'Reply'), ('ALIAS', 'Alias')], default='REPLY', max_length=32)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date changed')),
                ('popularity', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
